# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180225_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='theme_image',
            field=models.ImageField(default=2, upload_to=b''),
            preserve_default=False,
        ),
    ]
