# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_text_theme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreHypeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('picture1', models.ImageField(upload_to=b'')),
                ('picture2', models.ImageField(upload_to=b'')),
                ('picture3', models.ImageField(upload_to=b'')),
                ('picture4', models.ImageField(upload_to=b'')),
                ('picture5', models.ImageField(upload_to=b'')),
                ('picture6', models.ImageField(upload_to=b'')),
                ('picture7', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
