# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prehypeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='prehypeevent',
            name='picture8',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prehypeevent',
            name='picture9',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
